name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  inclusion:
    uses: salesforcecli/github-workflows/.github/workflows/inclusionTest.yml@main
